version: "3.8"
services:
    springapp:
        image: springapp
        build: /
        restart: always
        depends_on:
            elasticsearch:
                condition: service_healthy
        expose:
            - 8080
        ports:
            - 0.0.0.0:8080:8080/tcp
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        container_name: elasticsearch
        environment:
          - discovery.type=single-node
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://0.0.0.0:9200"]
          interval: 30s
          timeout: 10s
          retries: 5
        ulimits:
          memlock:
            hard: -1
            soft: -1
        ports:
            - 9200:9200